[[link]]
source = "wezterm/wezterm.lua"
target = "~/.config/wezterm/wezterm.lua"

[[link]]
source = "zsh/.zshrc"
target = "~/.zshrc"
host = ["mac"]

[[link]]
source = "zsh/module"
target = "~/.zsh_module"
host = ["mac"]

[[link]]
source = "zsh/sheldon/plugins.toml"
target = "~/.config/sheldon/plugins.toml"
host = ["mac"]

[[link]]
source = "tmux/.tmux.conf"
target = "~/.tmux.conf"

[[link]]
source = "tmux/tmux_module"
target = "~/tmux"

[[link]]
source = "nvim"
target = "~/.config/nvim"
[link.windows]
target = "~/AppData/Local/nvim"

[[link]]
source = "pwsh/Microsoft.PowerShell_profile.ps1"
target = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
host = ["windows"]

[[link]]
source = "pwsh/module"
target = "~/Documents/PowerShell/module"
host = ["windows"]
