set -g status-position top
set -g status-interval 30

set -g status-style "bg=#222436,fg=#d6e0fc"
set -g message-style "bg=#8ab0ff,fg=#202030"
set -g mode-style "bg=#ffbb5b,fg=#202030,bold"
set -g pane-border-style "fg=#46466a"
set -g pane-active-border-style "fg=#8ab0ff"

set -g @status-center-command "echo center"

set -g status-justify centre
set -g status-left-length 48
set -g status-right-length 16
set -g status-left "#[fg=#8ab0ff,bg=#222436]#[fg=#202030,bg=#8ab0ff,bold] #S | #{?#{n:window_name},#W,win-#I} #[fg=#8ab0ff,bg=#222436]"
set -g status-right "#[fg=#71dfff,bg=#222436]#[fg=#202030,bg=#71dfff,bold] %H:%M #[fg=#71dfff,bg=#222436]"

set -g window-status-separator ""
set -g window-status-style "fg=#a5a5cc,bg=#46466a"
set -g window-status-current-style "fg=#202030,bg=#ffbb5b,bold"
set -g window-status-last-style "fg=#a5a5cc,bg=#46466a"
set -g window-status-activity-style "fg=#a5a5cc,bg=#46466a"
set -g window-status-bell-style "fg=#a5a5cc,bg=#46466a"
set -g window-status-format ""
set -g window-status-current-format "#[fg=#d6e0fc,bg=#222436]#(#{@status-center-command})"
