shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

# local plugins
[plugins.alias]
local = "~/.zsh_module/alias"

[plugins.abbr]
local = "~/.zsh_module/abbr"

[plugins.zoxide]
local = "~/.zsh_module/zoxide"
